mysite/food/urls.py
from django.urls import path
from . import views

app_name = "food"
urlpatterns = [
    path("", views.index.as_view(), name="index"),
    path("<int:pk>/", views.detail.as_view(), name="detail"),
    path("add/", views.add_item.as_view(), name="add_item"),
    path("edit/<int:item_id>", views.edit_item, name="edit_item"),
    path("delete/<int:item_id>", views.delete_item, name="delete_item"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("food/", include("food.urls")),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        authentication_views.LoginView.as_view(template_name="login.html"),
        name="login",
    ),
    path(
        "logout/",
        authentication_views.LogoutView.as_view(template_name="logout.html"),
        name="logout",
    ),
    path("profile/", user_views.profile, name="profile"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Item(models.Model):
    def __str__(self):
        return self.item_name

    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_img = models.CharField(
        max_length=500,
        default="https://www.food4fuel.com/wp-content/uploads/woocommerce-placeholder-600x600.png",
    )

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="ProfilePic.jpg", upload_to="Profile_image/")
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

mysite/food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["item_name", "item_desc", "item_price", "item_img"]

mysite/users/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

mysite/food/views.py
from multiprocessing import context
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView

from .forms import ItemForm
from .models import Item


# Create your views here.


class index(ListView):
    model = Item
    template_name = "index.html"
    context_object_name = "items"


class detail(DetailView):
    model = Item
    template_name = "detail.html"


class add_item(CreateView):
    model = Item
    fields = ["item_name", "item_desc", "item_price", "item_img"]
    template_name = "item-form.html"
    success_url = reverse_lazy("food:index")

    def form_valid(self, form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)


def edit_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)

        if form.is_valid():
            form.save()
            return redirect("food:index")
    else:
        form = ItemForm(instance=item)
    return render(request, "item-form.html", {"form": form, "item": item})


def delete_item(request, item_id):
    item = Item.objects.get(id=item_id)
    if request.method == "POST":
        item.delete()
        return redirect("food:index")
    return render(request, "delete.html", {"item": item})

mysite/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Welcome {username}! You have registered successfully. "
            )
            return redirect("login")
    else:
        form = RegisterForm()
    return render(request, "user.html", {"form": form})


@login_required
def profile(request):
    return render(request, "profile.html")

mysite/food/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Homepage</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
    <header><nav class="navbar navbar-dark bg-dark navbar-expand-lg ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Foodies</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'food:add_item' %}">Add Item</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'profile' %}">Profile</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
    <form class="bg-dark border-dark" method="POST" action="{% url 'logout' %}" style="display: inline;">
        {% csrf_token %}
        <button class="bg-dark" type="submit">
            Logout
        </button>
    </form>
</li>
        {% else %}
         <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        
        
      </ul>
    </div>
  </div>
</nav></header>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tags}}">{{message}}</div>
{% endfor %}
{% endif %}
    {% block body %}
    {% endblock %}
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

mysite/food/templates/delete.html
{% extends "base.html" %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <h1>Are you sure that you want to delete {{item.item_name}}?</h1>
    <button type="submit" >Yes</button>
</form>

{% endblock %}

mysite/food/templates/detail.html
{% extends "base.html" %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img width="100%" src="{{object.item_img}}" class="card" >
        </div>
        <div class="col-md-6">
 <h1>{{object.item_name}}</h1> 
    <h2>{{object.item_desc}} </h2>
    <h3>${{object.item_price}}</h3>
        <h3>{{object.user_name}}</h3>
                    <a href="{% url 'food:edit_item' item.id %}" class="btn btn-success">Edit</a>
            <a href="{% url 'food:delete_item' item.id %}" class="btn btn-success">Delete</a>

       
        </div>
    </div>
</div>
   
{% endblock %}

mysite/food/templates/index.html
{% extends "base.html" %} 
{% block body %}
    
    {% for item in items %}
    <div class="row">
        <div class="col-md-3 offset-md-2">
            <img class="card"  width="100%" src="{{item.item_img}}" >
        </div>
        <div class="col-md-4">
            <h3>{{item.item_name}}</h3>
            <h5>{{item.item_desc}}</h5>
            <h6>${{item.item_price}}</h6>
            <h6>{{item.user_name}}</h6>

        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>
    {% endfor %}
   
    {% endblock %}
 

mysite/food/templates/item-form.html
{% extends "base.html" %}
{% block body %}
<form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>
</form>
{% endblock %}

mysite/users/templates/login.html
<form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" >Login</button>
</form>

mysite/users/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>You have successfully Logged Out</h1>
</body>
</html>

mysite/users/templates/profile.html
<h1>{{user.username}}</h1>
<img src=" {{user.profile.image.url}}" alt="">

mysite/users/templates/user.html
<form method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" > Sign Up </button>
</form>